### ISSUE TITLE
Set time nefunguje spravne.

### ISSUE THREAD

**Issue by dobrakmato** [pexelnet/starving#66]
```
[19:32:21 INFO]: pitkes22 issued server command: /time set day
[19:32:21 ERROR]: Could not pass event PlayerCommandPreprocessEvent to RPG v1.4.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1125) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_20]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_20]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
Caused by: java.lang.NumberFormatException: For input string: "day"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_20]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_20]
        at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_20]
        at eu.matejkormuth.rpgdavid.starving.listeners.HiddenCommandsListener.onCommand(HiddenCommandsListener.java:142) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_20]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_20]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
        ... 16 more

```

**Comment by dobrakmato** [comment]
Time set teraz podporuje aj `day` a `night` ako argument casu.

Implementovane v rewrite loadovania (este nepushnute).
