### ISSUE TITLE
Filtre su deafultne nefunkcne

### ISSUE THREAD

**Issue by dobrakmato** [pexelnet/starving#67]
```
[19:35:30 ERROR]: Could not pass event PlayerInteractEvent to RPG v1.4.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:189) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:692) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_20]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_20]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
Caused by: java.lang.NullPointerException
        at eu.matejkormuth.rpgdavid.starving.worldgen.filters.GrassFilter.apply(GrassFilter.java:80) ~[?:?]
        at eu.matejkormuth.rpgdavid.starving.worldgen.WandListener.performAction(WandListener.java:61) ~[?:?]
        at eu.matejkormuth.rpgdavid.starving.worldgen.WandListener.onWandInteract(WandListener.java:47) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_20]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_20]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
        ... 18 more
```

**Comment by dobrakmato** [comment]
Opravene v rewrite loadovanie (este nepushnute).
